# Generated by Django 5.2.9 on 2025-12-28 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Academic Journals Platform', help_text='Name of the publishing platform', max_length=200)),
                ('site_description', models.TextField(blank=True, help_text='Brief description of the platform')),
                ('tagline', models.CharField(blank=True, help_text='Site tagline or slogan', max_length=300)),
                ('logo', models.ImageField(blank=True, help_text='Site logo', null=True, upload_to='site/branding/')),
                ('favicon', models.ImageField(blank=True, help_text='Site favicon', null=True, upload_to='site/branding/')),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254)),
                ('contact_address', models.TextField(blank=True, help_text='Physical address')),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Social media links as JSON object')),
                ('footer_text', models.TextField(blank=True, help_text='Footer text (can include HTML)')),
                ('copyright_text', models.CharField(blank=True, help_text='Copyright notice', max_length=200)),
                ('meta_keywords', models.CharField(blank=True, help_text='Default meta keywords', max_length=500)),
                ('meta_description', models.TextField(blank=True, help_text='Default meta description', max_length=500)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly page identifier', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Page content (HTML supported)')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt for previews', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Is this page published?')),
                ('show_in_navigation', models.BooleanField(default=True, help_text='Show this page in navigation menus?')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in navigation')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', max_length=500)),
                ('template_name', models.CharField(blank=True, help_text='Optional custom template name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(blank=True, help_text='If set, this page belongs to a specific journal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='journals.journal')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['display_order', 'title'],
                'unique_together': {('journal', 'slug')},
            },
        ),
    ]
