# Generated by Django 5.2.9 on 2025-12-28 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.PositiveIntegerField(help_text='Issue number within the volume (e.g., 1, 2, 3...)')),
                ('title', models.CharField(blank=True, help_text='Optional issue title (e.g., "Special Issue on Climate Change")', max_length=300)),
                ('publication_date', models.DateField(blank=True, help_text='Date this issue was published', null=True)),
                ('description', models.TextField(blank=True, help_text='Description or editorial note for this issue')),
                ('cover_image', models.ImageField(blank=True, help_text='Issue cover image', null=True, upload_to='issues/covers/')),
                ('is_special_issue', models.BooleanField(default=False, help_text='Is this a special themed issue?')),
                ('special_issue_title', models.CharField(blank=True, help_text='Title for special issues (e.g., "Focus on Renewable Energy")', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Is this issue visible to the public?')),
                ('is_current', models.BooleanField(default=False, help_text='Is this the current/latest issue? (for homepage display)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.ForeignKey(help_text='The volume this issue belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='volumes.volume')),
            ],
            options={
                'verbose_name': 'issue',
                'verbose_name_plural': 'issues',
                'ordering': ['-volume__year', '-volume__volume_number', '-issue_number'],
                'unique_together': {('volume', 'issue_number')},
            },
        ),
    ]
