# Generated by Django 5.2.9 on 2025-12-28 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Author first/given name', max_length=100)),
                ('last_name', models.CharField(help_text='Author last/family name', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Author email address', max_length=254)),
                ('orcid_id', models.CharField(blank=True, help_text='ORCID identifier (e.g., 0000-0002-1825-0097)', max_length=50, verbose_name='ORCID ID')),
                ('affiliation', models.TextField(blank=True, help_text='Primary institutional affiliation')),
                ('department', models.CharField(blank=True, help_text='Department or division', max_length=200)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Short biography')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Full article title')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=300)),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier (e.g., 10.1000/xyz123)', max_length=100, verbose_name='DOI')),
                ('article_type', models.CharField(choices=[('research', 'Research Article'), ('review', 'Review Article'), ('case_report', 'Case Report'), ('short_communication', 'Short Communication'), ('letter', 'Letter to the Editor'), ('editorial', 'Editorial'), ('commentary', 'Commentary'), ('perspective', 'Perspective'), ('book_review', 'Book Review'), ('erratum', 'Erratum'), ('retraction', 'Retraction'), ('other', 'Other')], default='research', help_text='Type of article', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retracted', 'Retracted')], default='draft', help_text='Publication status', max_length=20)),
                ('abstract', models.TextField(blank=True, help_text='Article abstract (plain text or simple HTML)')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='List of keywords as JSON array')),
                ('page_start', models.CharField(blank=True, help_text='Starting page number', max_length=20)),
                ('page_end', models.CharField(blank=True, help_text='Ending page number', max_length=20)),
                ('article_number', models.CharField(blank=True, help_text='Article number (for journals using article numbers instead of pages)', max_length=50)),
                ('received_date', models.DateField(blank=True, help_text='Date manuscript was received', null=True)),
                ('revised_date', models.DateField(blank=True, help_text='Date revised manuscript was received', null=True)),
                ('accepted_date', models.DateField(blank=True, help_text='Date manuscript was accepted', null=True)),
                ('published_date', models.DateField(blank=True, help_text='Date article was published online', null=True)),
                ('is_open_access', models.BooleanField(default=True, help_text='Is this article open access?')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this article on the homepage?')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times article has been viewed')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times PDF has been downloaded')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(help_text='The issue this article belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='issues.issue')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('xml', 'XML Source'), ('pdf', 'PDF'), ('supplementary', 'Supplementary Material'), ('data', 'Data File')], help_text='Type of file', max_length=20)),
                ('file', models.FileField(help_text='The uploaded file', upload_to='articles/files/')),
                ('original_filename', models.CharField(blank=True, help_text='Original filename as uploaded', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary file of its type?')),
                ('description', models.CharField(blank=True, help_text='Description of this file', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='articles.article')),
            ],
            options={
                'verbose_name': 'article file',
                'verbose_name_plural': 'article files',
                'ordering': ['file_type', '-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleHTMLContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_xml', models.TextField(blank=True, help_text='Original XML content')),
                ('abstract_html', models.TextField(blank=True, help_text='Parsed abstract as HTML')),
                ('body_html', models.TextField(blank=True, help_text='Parsed article body as HTML')),
                ('references_html', models.TextField(blank=True, help_text='Parsed references section as HTML')),
                ('acknowledgments_html', models.TextField(blank=True, help_text='Parsed acknowledgments as HTML')),
                ('figures_json', models.JSONField(blank=True, default=list, help_text='Metadata about figures extracted from XML')),
                ('tables_json', models.JSONField(blank=True, default=list, help_text='Metadata about tables extracted from XML')),
                ('parsing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Status of XML parsing', max_length=20)),
                ('parsing_errors', models.TextField(blank=True, help_text='Error messages from parsing (if any)')),
                ('parsed_at', models.DateTimeField(blank=True, help_text='When the XML was last parsed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='html_content', to='articles.article')),
            ],
            options={
                'verbose_name': 'article HTML content',
                'verbose_name_plural': 'article HTML contents',
            },
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_order', models.PositiveIntegerField(default=1, help_text='Order of this author in the author list')),
                ('is_corresponding', models.BooleanField(default=False, help_text='Is this the corresponding author?')),
                ('author_contribution', models.TextField(blank=True, help_text="Description of author's contribution")),
                ('affiliation_override', models.TextField(blank=True, help_text='Override affiliation for this specific article')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_authors', to='articles.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_authors', to='articles.author')),
            ],
            options={
                'verbose_name': 'article author',
                'verbose_name_plural': 'article authors',
                'ordering': ['author_order'],
                'unique_together': {('article', 'author')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(help_text='Article authors', related_name='articles', through='articles.ArticleAuthor', to='articles.author'),
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure_id', models.CharField(blank=True, help_text='Figure ID from XML (e.g., "fig1")', max_length=100)),
                ('figure_number', models.PositiveIntegerField(default=1, help_text='Figure number for display')),
                ('label', models.CharField(blank=True, help_text='Figure label (e.g., "Figure 1")', max_length=100)),
                ('caption', models.TextField(blank=True, help_text='Figure caption')),
                ('image', models.ImageField(help_text='Figure image file', upload_to='articles/figures/')),
                ('original_filename', models.CharField(blank=True, help_text='Original image filename', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display in article')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='articles.article')),
            ],
            options={
                'verbose_name': 'figure',
                'verbose_name_plural': 'figures',
                'ordering': ['display_order', 'figure_number'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(blank=True, help_text='Table ID from XML (e.g., "tbl1")', max_length=100)),
                ('table_number', models.PositiveIntegerField(default=1, help_text='Table number for display')),
                ('label', models.CharField(blank=True, help_text='Table label (e.g., "Table 1")', max_length=100)),
                ('caption', models.TextField(blank=True, help_text='Table caption')),
                ('table_html', models.TextField(blank=True, help_text='Table content as HTML')),
                ('footnotes', models.TextField(blank=True, help_text='Table footnotes')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display in article')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='articles.article')),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'tables',
                'ordering': ['display_order', 'table_number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('issue', 'slug')},
        ),
    ]
