# Generated by Django 4.2.7 on 2026-02-05 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        ('volumes', '0001_initial'),
        ('journals', '0012_journalindexing_category'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='article',
            name='article_id_code',
            field=models.CharField(blank=True, help_text='Custom article identifier (e.g., JS-2024-001)', max_length=50, verbose_name='Article ID'),
        ),
        migrations.AddField(
            model_name='article',
            name='epub_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/epub/', verbose_name='ePUB File'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_special_issue',
            field=models.BooleanField(default=False, help_text='Tick if this article belongs to a Special Issue', verbose_name='Is Special Issue'),
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(blank=True, help_text='The journal this article belongs to (required)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_direct', to='journals.journal'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords_display',
            field=models.TextField(blank=True, help_text='Keywords to be displayed on the website', verbose_name='Display Keywords'),
        ),
        migrations.AddField(
            model_name='article',
            name='license_text',
            field=models.CharField(default='CC BY License', help_text='Licensing information', max_length=255, verbose_name='License'),
        ),
        migrations.AddField(
            model_name='article',
            name='mobi_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/mobi/', verbose_name='Mobi File'),
        ),
        migrations.AddField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/pdf/', verbose_name='PDF File'),
        ),
        migrations.AddField(
            model_name='article',
            name='prc_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/prc/', verbose_name='PRC File'),
        ),
        migrations.AddField(
            model_name='article',
            name='volume',
            field=models.ForeignKey(blank=True, help_text='The volume this article belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='volumes.volume'),
        ),
        migrations.AddField(
            model_name='article',
            name='xml_file',
            field=models.FileField(blank=True, help_text='XML source file for parsing', null=True, upload_to='articles/xml/', verbose_name='XML File'),
        ),
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, help_text='The issue this article belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='issues.issue'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='List of keywords for SEO as JSON array', verbose_name='SEO Keywords'),
        ),
    ]
