# Generated by Django 4.2.7 on 2026-02-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleauthor',
            name='affiliation_override',
        ),
    ]
