# Generated by Django 4.2.7 on 2026-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_articleauthor_affiliation_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_preface',
            field=models.BooleanField(default=False, help_text='Tick if this article is the preface/editorial for the volume', verbose_name='Is Preface'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id_code',
            field=models.CharField(blank=True, db_index=True, help_text='Custom article identifier (e.g., JS-2024-001)', max_length=50, verbose_name='Article ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, db_index=True, help_text='Digital Object Identifier (e.g., 10.1000/xyz123)', max_length=100, verbose_name='DOI'),
        ),
    ]
