# Generated by Django 4.2.7 on 2026-02-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_is_preface_alter_article_article_id_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archive', 'Archive')], default='draft', help_text='Publication status', max_length=20),
        ),
    ]
