# Generated by Django 4.2.7 on 2026-02-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='license_text',
            field=models.TextField(default='CC BY License', help_text='Licensing information (supports HTML for links)', verbose_name='License'),
        ),
    ]
