# Generated by Django 4.2.7 on 2026-02-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_license_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bib_file',
            field=models.FileField(blank=True, help_text='BibTeX citation file', null=True, upload_to='articles/citations/', verbose_name='BibTeX Citation'),
        ),
        migrations.AddField(
            model_name='article',
            name='cite_as',
            field=models.TextField(blank=True, help_text='Custom citation text. If empty, a default citation will be generated.', verbose_name='Cite As'),
        ),
        migrations.AddField(
            model_name='article',
            name='endnote_file',
            field=models.FileField(blank=True, help_text='EndNote citation file', null=True, upload_to='articles/citations/', verbose_name='EndNote Citation'),
        ),
        migrations.AddField(
            model_name='article',
            name='ris_file',
            field=models.FileField(blank=True, help_text='RIS citation file', null=True, upload_to='articles/citations/', verbose_name='RIS Citation'),
        ),
    ]
