# Generated by Django 5.2.9 on 2026-02-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_bib_file_article_cite_as_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bib_file',
            field=models.FileField(blank=True, help_text='BibTeX citation file', max_length=500, null=True, upload_to='articles/citations/', verbose_name='BibTeX Citation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='endnote_file',
            field=models.FileField(blank=True, help_text='EndNote citation file', max_length=500, null=True, upload_to='articles/citations/', verbose_name='EndNote Citation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='epub_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='articles/epub/', verbose_name='ePUB File'),
        ),
        migrations.AlterField(
            model_name='article',
            name='mobi_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='articles/mobi/', verbose_name='Mobi File'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='articles/pdf/', verbose_name='PDF File'),
        ),
        migrations.AlterField(
            model_name='article',
            name='prc_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='articles/prc/', verbose_name='PRC File'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ris_file',
            field=models.FileField(blank=True, help_text='RIS citation file', max_length=500, null=True, upload_to='articles/citations/', verbose_name='RIS Citation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='xml_file',
            field=models.FileField(blank=True, help_text='XML source file for parsing', max_length=500, null=True, upload_to='articles/xml/', verbose_name='XML File'),
        ),
        migrations.AlterField(
            model_name='articlefile',
            name='file',
            field=models.FileField(help_text='The uploaded file', max_length=500, upload_to='articles/files/'),
        ),
    ]
