# Generated by Django 5.2.9 on 2026-02-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_bib_file_alter_article_endnote_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='image',
            field=models.ImageField(help_text='Figure image file', max_length=500, upload_to='articles/figures/'),
        ),
    ]
