# Generated by Django 5.2.9 on 2026-02-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_figure_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cite_score',
            field=models.CharField(blank=True, help_text='Cite Score value', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='cite_score_url',
            field=models.URLField(blank=True, help_text='URL for Cite Score'),
        ),
        migrations.AddField(
            model_name='article',
            name='scopus_score',
            field=models.CharField(blank=True, help_text='Scopus Score value', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='scopus_score_url',
            field=models.URLField(blank=True, help_text='URL for Scopus Score'),
        ),
    ]
