# Generated by Django 5.2.9 on 2026-02-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_cite_score_article_cite_score_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='crossmark_logo',
            field=models.ImageField(blank=True, help_text='Crossmark or other top logo', max_length=500, null=True, upload_to='articles/logos/'),
        ),
        migrations.AddField(
            model_name='article',
            name='crossmark_url',
            field=models.URLField(blank=True, help_text='URL for the Crossmark/top logo'),
        ),
        migrations.AddField(
            model_name='article',
            name='top_highlighted_line',
            field=models.TextField(blank=True, help_text='Red highlighted text shown at the very top of the article'),
        ),
    ]
