# Generated by Django 5.2.9 on 2025-12-28 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.PositiveIntegerField(help_text='Volume number (e.g., 1, 2, 3...)')),
                ('title', models.CharField(blank=True, help_text='Optional volume title (e.g., "Special Anniversary Volume")', max_length=300)),
                ('year', models.PositiveIntegerField(help_text='Publication year for this volume')),
                ('description', models.TextField(blank=True, help_text='Description or notes about this volume')),
                ('cover_image', models.ImageField(blank=True, help_text='Volume cover image', null=True, upload_to='volumes/covers/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this volume visible to the public?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(help_text='The journal this volume belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='journals.journal')),
            ],
            options={
                'verbose_name': 'volume',
                'verbose_name_plural': 'volumes',
                'ordering': ['-year', '-volume_number'],
                'unique_together': {('journal', 'volume_number')},
            },
        ),
    ]
