# Generated by Django 5.2.9 on 2026-02-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Is this volume archived?'),
        ),
    ]
