# Generated by Django 5.2.9 on 2025-12-28 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject name (e.g., "Molecular Biology")', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this subject area')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display this subject')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent subject for hierarchical organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='journals.subject')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Full journal title', max_length=500)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (used in routes like /{slug}/)', max_length=200, unique=True)),
                ('short_title', models.CharField(blank=True, help_text='Abbreviated journal title', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Full description of the journal')),
                ('short_description', models.TextField(blank=True, help_text='Brief description for listings and cards', max_length=500)),
                ('issn_print', models.CharField(blank=True, help_text='Print ISSN (e.g., 1234-5678)', max_length=20, verbose_name='ISSN (Print)')),
                ('issn_online', models.CharField(blank=True, help_text='Online ISSN (e.g., 1234-5678)', max_length=20, verbose_name='ISSN (Online)')),
                ('cover_image', models.ImageField(blank=True, help_text='Journal cover image for display', null=True, upload_to='journals/covers/')),
                ('logo', models.ImageField(blank=True, help_text='Journal logo', null=True, upload_to='journals/logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon for browser tab', null=True, upload_to='journals/favicons/')),
                ('primary_color', models.CharField(default='#1a365d', help_text='Primary brand color (hex code, e.g., #1a365d)', max_length=7)),
                ('secondary_color', models.CharField(default='#2b6cb0', help_text='Secondary brand color (hex code)', max_length=7)),
                ('editor_in_chief', models.CharField(blank=True, help_text='Name of the Editor-in-Chief', max_length=200)),
                ('publisher', models.CharField(blank=True, help_text='Publisher name', max_length=200)),
                ('founding_year', models.PositiveIntegerField(blank=True, help_text='Year the journal was founded', null=True)),
                ('frequency', models.CharField(blank=True, help_text='Publication frequency (e.g., "Quarterly", "Monthly")', max_length=100)),
                ('aims_and_scope', models.TextField(blank=True, help_text='Journal aims and scope (can include HTML)')),
                ('author_guidelines', models.TextField(blank=True, help_text='Guidelines for authors submitting manuscripts')),
                ('peer_review_policy', models.TextField(blank=True, help_text='Description of the peer review process')),
                ('contact_email', models.EmailField(blank=True, help_text='Journal contact email', max_length=254)),
                ('website_url', models.URLField(blank=True, help_text='External website URL (if any)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this journal currently active?')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this journal on the homepage?')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (defaults to journal title)', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', max_length=500)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords (comma-separated)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(blank=True, help_text='Subject areas this journal covers', related_name='journals', to='journals.subject')),
            ],
            options={
                'verbose_name': 'journal',
                'verbose_name_plural': 'journals',
                'ordering': ['title'],
            },
        ),
    ]
