# Generated by Django 5.2.9 on 2026-01-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Announcement headline', max_length=300)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=300, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary for listing cards (2-3 lines)', max_length=500)),
                ('content', models.TextField(help_text='Full content of the announcement (can include HTML)')),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the announcement', null=True, upload_to='announcements/images/')),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Display this announcement on the homepage')),
                ('is_published', models.BooleanField(default=False, help_text='Is this announcement published?')),
                ('author_name', models.CharField(blank=True, help_text='Author or source of the announcement', max_length=200)),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication date (for ordering)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'announcement',
                'verbose_name_plural': 'announcements',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorporateAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organization name (e.g., "Crossref", "DOAJ")', max_length=200)),
                ('logo', models.ImageField(help_text='Logo image for the organization', upload_to='affiliations/logos/')),
                ('url', models.URLField(blank=True, help_text='Link to the organization website')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this affiliation on the site?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'corporate affiliation',
                'verbose_name_plural': 'corporate affiliations',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
