# Generated by Django 4.2.7 on 2026-02-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_announcement_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTACard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Card title (e.g., "Become An Editorial Board Member")', max_length=200)),
                ('highlight_text', models.CharField(blank=True, help_text='Text to highlight in a different color (e.g., "Editorial Board Member")', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle (e.g., "(Special Issue)")', max_length=200)),
                ('button_text', models.CharField(default='Register Here', help_text='Button text', max_length=50)),
                ('image', models.ImageField(help_text='Card background/image', upload_to='cta_cards/')),
                ('link_url', models.URLField(default='#', help_text='URL to link to when card is clicked')),
                ('highlight_color', models.CharField(default='orange-500', help_text='Tailwind color class for highlight (e.g., orange-500, red-500, blue-500, teal-500)', max_length=50)),
                ('button_color', models.CharField(default='gray-200', help_text='Tailwind color class for button background', max_length=50)),
                ('button_text_color', models.CharField(default='gray-800', help_text='Tailwind color class for button text', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this card is displayed on the homepage')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which cards are displayed (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CTA Card',
                'verbose_name_plural': 'CTA Cards',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
