# Generated by Django 4.2.7 on 2026-02-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_ctacard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctacard',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='ctacard',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='ctacard',
            name='button_text_color',
        ),
        migrations.RemoveField(
            model_name='ctacard',
            name='highlight_color',
        ),
        migrations.RemoveField(
            model_name='ctacard',
            name='highlight_text',
        ),
        migrations.RemoveField(
            model_name='ctacard',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='ctacard',
            name='title',
        ),
        migrations.AlterField(
            model_name='ctacard',
            name='image',
            field=models.ImageField(help_text='Card image', upload_to='cta_cards/'),
        ),
        migrations.AlterField(
            model_name='ctacard',
            name='link_url',
            field=models.URLField(default='#', help_text='URL to link to when image is clicked'),
        ),
    ]
