# Generated by Django 4.2.7 on 2026-02-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_remove_ctacard_button_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='editorial_board',
            field=models.TextField(blank=True, help_text='Editorial board members (can include HTML)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='flyer_pdf',
            field=models.FileField(blank=True, help_text='PDF flyer for the journal', null=True, upload_to='journals/flyers/'),
        ),
        migrations.AddField(
            model_name='journal',
            name='indexing',
            field=models.TextField(blank=True, help_text='Indexing and abstracting information (can include HTML)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='open_thematic_issue',
            field=models.TextField(blank=True, help_text='Information about open thematic issues (can include HTML)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='submission_url',
            field=models.URLField(blank=True, help_text='URL for "Submit your work" button'),
        ),
    ]
