# Generated by Django 4.2.7 on 2026-02-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_journal_editorial_board_journal_flyer_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(blank=True, help_text='Full description/About section of the journal (supports HTML)', verbose_name='About Journal'),
        ),
    ]
