# Generated by Django 4.2.7 on 2026-02-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_alter_journal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='editorial_board',
        ),
        migrations.CreateModel(
            name='EditorialBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='Member role (e.g., Editor-in-Chief, Associate Editor)', max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Member photo', null=True, upload_to='editorial_board/')),
                ('department', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='School/College/University')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief bio or description (supports HTML/Rich Text)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order within the designation or overall')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(help_text='The journal this member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='editorial_board_members', to='journals.journal')),
            ],
            options={
                'verbose_name': 'editorial board member',
                'verbose_name_plural': 'editorial board members',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
