# Generated by Django 4.2.7 on 2026-02-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_remove_journal_editorial_board_editorialboardmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctacard',
            options={'ordering': ['display_order', 'created_at'], 'verbose_name': 'CTA card', 'verbose_name_plural': 'CTA cards'},
        ),
        migrations.AlterField(
            model_name='ctacard',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of appearance (lower numbers first)'),
        ),
        migrations.AlterField(
            model_name='ctacard',
            name='image',
            field=models.ImageField(help_text='Image to display on the card', upload_to='cta_cards/'),
        ),
        migrations.AlterField(
            model_name='ctacard',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this card on the homepage?'),
        ),
        migrations.AlterField(
            model_name='ctacard',
            name='link_url',
            field=models.URLField(default='#', help_text='URL to redirect when the card is clicked', verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='flyer_pdf',
            field=models.FileField(blank=True, help_text='PDF flyer for the journal', null=True, upload_to='journals/flyers/', verbose_name='Journal Flyer (PDF)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='indexing',
            field=models.TextField(blank=True, help_text='Indexing information (can include HTML)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='open_thematic_issue',
            field=models.TextField(blank=True, help_text='Open thematic issue information (can include HTML)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='submission_url',
            field=models.URLField(blank=True, help_text='URL for submitting work (e.g. OJS or external form)', verbose_name='Submission URL'),
        ),
    ]
