# Generated by Django 4.2.7 on 2026-02-03 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0009_alter_ctacard_options_alter_ctacard_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalIndexing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the indexing service (e.g. Scopus)', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Logo of the indexing service', null=True, upload_to='journals/indexing_logos/')),
                ('url', models.URLField(blank=True, help_text='Link to the journal listing on this indexing service')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of appearance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(help_text='The journal this indexing entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='indexing_entries', to='journals.journal')),
            ],
            options={
                'verbose_name': 'journal indexing',
                'verbose_name_plural': 'journal indexings',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
