# Generated by Django 4.2.7 on 2026-02-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0010_journalindexing'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='editor_in_chief_image',
            field=models.ImageField(blank=True, help_text='Photo of the Editor-in-Chief for avatar display', null=True, upload_to='journals/editors/', verbose_name='Editor-in-Chief Photo'),
        ),
    ]
