# Generated by Django 4.2.7 on 2026-02-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0011_journal_editor_in_chief_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalindexing',
            name='category',
            field=models.CharField(blank=True, help_text='Category/Heading for grouping (e.g. "Research Integrity & Quality Assurance")', max_length=200),
        ),
    ]
