# Generated by Django 4.2.7 on 2026-02-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0012_journalindexing_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTAButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('editorial-board', 'Become a Editorial Board Member'), ('reviewer', 'Become a Reviewer'), ('call-for-editors', 'Call For Editors'), ('section-editor', 'Become a section Editor')], unique=True)),
                ('label', models.CharField(max_length=255)),
                ('notification_email', models.EmailField(help_text='Form submissions will be sent to this email', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CTA Button',
                'verbose_name_plural': 'CTA Buttons',
            },
        ),
        migrations.CreateModel(
            name='CTAFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Prof.', 'Prof.'), ('Dr.', 'Dr.')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=255, verbose_name='Last Academic Qualification')),
                ('affiliation', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=255, verbose_name='Field of Expertise')),
                ('orcid_id', models.CharField(blank=True, max_length=50, verbose_name='ORCID ID')),
                ('scopus_id', models.CharField(blank=True, max_length=50, verbose_name='Scopus ID')),
                ('cv_file', models.FileField(upload_to='cta_submissions/cvs/', verbose_name='Upload CV')),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='journals.ctabutton')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journals.journal')),
            ],
            options={
                'verbose_name': 'CTA Form Submission',
                'verbose_name_plural': 'CTA Form Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
