# Generated by Django 4.2.7 on 2026-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0013_ctabutton_ctaformsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='issn_online',
            field=models.CharField(blank=True, db_index=True, help_text='Online ISSN (e.g., 1234-5678)', max_length=20, verbose_name='ISSN (Online)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn_print',
            field=models.CharField(blank=True, db_index=True, help_text='Print ISSN (e.g., 1234-5678)', max_length=20, verbose_name='ISSN (Print)'),
        ),
    ]
