# Generated by Django 4.2.7 on 2026-02-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0014_alter_journal_issn_online_alter_journal_issn_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='login_url',
            field=models.URLField(blank=True, help_text='URL for author login', verbose_name='Login URL'),
        ),
    ]
