# Generated by Django 4.2.7 on 2026-02-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0015_journal_login_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Wide banner image for the journal homepage hero section', null=True, upload_to='journals/banners/'),
        ),
    ]
