# Generated by Django 5.2.9 on 2026-02-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0016_journal_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the announcement', max_length=500, null=True, upload_to='announcements/images/'),
        ),
        migrations.AlterField(
            model_name='corporateaffiliation',
            name='logo',
            field=models.ImageField(help_text='Logo image for the organization', max_length=500, upload_to='affiliations/logos/'),
        ),
        migrations.AlterField(
            model_name='ctacard',
            name='image',
            field=models.ImageField(help_text='Image to display on the card', max_length=500, upload_to='cta_cards/'),
        ),
        migrations.AlterField(
            model_name='ctaformsubmission',
            name='cv_file',
            field=models.FileField(max_length=500, upload_to='cta_submissions/cvs/', verbose_name='Upload CV'),
        ),
        migrations.AlterField(
            model_name='editorialboardmember',
            name='image',
            field=models.ImageField(blank=True, help_text='Member photo', max_length=500, null=True, upload_to='editorial_board/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Wide banner image for the journal homepage hero section', max_length=500, null=True, upload_to='journals/banners/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Journal cover image for display', max_length=500, null=True, upload_to='journals/covers/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='editor_in_chief_image',
            field=models.ImageField(blank=True, help_text='Photo of the Editor-in-Chief for avatar display', max_length=500, null=True, upload_to='journals/editors/', verbose_name='Editor-in-Chief Photo'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon for browser tab', max_length=500, null=True, upload_to='journals/favicons/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='flyer_pdf',
            field=models.FileField(blank=True, help_text='PDF flyer for the journal', max_length=500, null=True, upload_to='journals/flyers/', verbose_name='Journal Flyer (PDF)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='logo',
            field=models.ImageField(blank=True, help_text='Journal logo', max_length=500, null=True, upload_to='journals/logos/'),
        ),
        migrations.AlterField(
            model_name='journalindexing',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo of the indexing service', max_length=500, null=True, upload_to='journals/indexing_logos/'),
        ),
    ]
