# Generated by Django 5.2.9 on 2026-02-14 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0017_alter_announcement_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The question text')),
                ('answer', models.TextField(help_text='The answer text (supports HTML)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of appearance')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(help_text='The journal this FAQ belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='journals.journal')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
