# Generated by Django 5.2.9 on 2026-02-14 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0018_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'indexing platform',
                'verbose_name_plural': 'indexing platforms',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalIndexingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL to the journal on this indexing platform')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_indexing_links', to='journals.journal')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_links', to='journals.indexingplatform')),
            ],
            options={
                'verbose_name': 'journal indexing link',
                'verbose_name_plural': 'journal indexing links',
                'unique_together': {('platform', 'journal')},
            },
        ),
    ]
